### ISSUE TITLE
Spam & Bot Filteration

### ISSUE THREAD

**Issue by zainasir** [jameskirkby/serverless-contact-form#2]
Hi  @jameskirkby,
I found your contact-form extremely helpful. However, it would be even better if you could show me how to implement spam and bot filtration.

Thanks.

**Comment by jameskirkby** [comment]
Hey @zainasir 

This article has a fairly good rundown of how it can be done: https://medium.com/aws-factory/recaptcha-form-with-an-amazon-aws-serverless-backend-environment-809cdb788424

A few things to note:
- You'll need to add recaptcha to the HTML in the frontend
- You'll probably want to use a newer version of nodejs. I wrote this example ~4 years ago so it's a bit outdated. [You can change that here](https://github.com/jameskirkby/serverless-contact-form/blob/master/serverless.yml#L18)
- You'll want to change the [handler to be an async function](https://github.com/jameskirkby/serverless-contact-form/blob/master/handler.js#L26), same as in the medium article linked above
- [You can probably add the recaptcha check on around line 113](https://github.com/jameskirkby/serverless-contact-form/blob/master/handler.js#L113):

```js
// Check recaptcha is in form data
if (!event.body['g-recaptcha-response']) {
  return callback(null, {
    statusCode: 500,
     body: 'recaptcha not in data.'
   })
} else {
  // check recaptcha is valid
  const verifyResult = await axios.post(reCapUrl, {
    secret: reCaptchaSecret,
    response: event.body['g-recaptcha-response']
  });
  console.log(verifyResult);
  if (verifyResult.status !== 200) { 
    return callback(null, {
       statusCode: 500,
       body: 'recaptcha failed.'
     })       
  }
}
```

**Comment by zainasir** [comment]
Thank you so much for your help!
